package User;
//ENUMS TO REPRESENT PERMISSIONS FOR USERTYPES
public enum Permission {
    
    //GENERAL PERMISSIONS
    VIEW_PROFILE,
    MAKE_PAYMENT,
    VIEW_FINANCE_HISTORY,
    
    //ADMIN PERMISSIONS
    EDIT_PROFILE,
    REGISTER_ACCOUNT,
    
    //RENTAL PERMISSIONS
    RENT,
    RETURN,
    VIEW_RENTAL,
    
    //EQUIPMENT PERMISSIONS
    VIEW_EQUIPMENT,
    ADD_EQUIPMENT,
    EDIT_EQUIPMENT,
    ADD_CATEGORY,
    EDIT_CATEGORY,
    
    //USER TYPE EDITING PERMISSIONS
//    VIEW_USER_TYPE,
//    ADD_USER_TYPE,
//    EDIT_USER_TYPE,
//    EDIT_DISCOUNT
    
}
